---
version: "3.8"
services:
  app:
    build: .
    container_name: express-app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres-user:postgres-user@localhost:5432/nodejs-prisma-redis-dockerize?schema=public
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres-docker
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password
      POSTGRES_DB: nodejs-prisma-redis-dockerize
    ports:
      - 5432:5432
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - 8000:8000
